# Generated by Django 5.0.6 on 2024-06-03 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQRUPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('upi_id', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=4)),
                ('txn_id', models.CharField(max_length=25)),
                ('payment_image', models.BinaryField()),
                ('payment_method', models.CharField(choices=[('Paytm_UPI', 'Paytm UPI'), ('PhonePe_UPI', 'Phonepe UPI'), ('GPay_UPI', 'GPay UPI'), ('other', 'other')], max_length=50)),
                ('upi_id', models.CharField(blank=True, max_length=25)),
                ('status', models.CharField(blank=True, choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=50)),
                ('user', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
