# Generated by Django 5.0.6 on 2024-06-03 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentform',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
