# Generated by Django 5.0.6 on 2024-06-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentform',
            name='txn_id',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawalhistory',
            name='withdrawal_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
