# Generated by Django 5.0.6 on 2024-06-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_alter_paymentform_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentform',
            name='payment_image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentqrupi',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
